name: PR Deadline Labeler

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 0 * * *'
  pull_request_review:
    types: [submitted]

env:
  DEADLINE_DAYS: 5

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Attach label on PR opened
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-date: ${{ github.event.pull_request.created_at }}
          pr-number: ${{ github.event.pull_request.number }}
          deadline-days: ${{ env.DEADLINE_DAYS }}

      - name: Update labels on schedule
        if: github.event_name == 'schedule'
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-date: ${{ github.event.pull_request.created_at }}
          deadline-days: ${{ env.DEADLINE_DAYS }}

      - name: Reset label on review submitted
        if: github.event_name == 'pull_request_review'
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-date: ${{ github.event.review.submitted_at }}
          pr-number: ${{ github.event.pull_request.number }}
          deadline-days: ${{ env.DEADLINE_DAYS }}
